sudo: true
dist: trusty
language: java
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN
jdk:
  - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - cd single-board-computers/raspberry-pi/spi/max7219/led-matrix/8x8/web-app
  - mvn verify
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
