- name: Create the directory for the application binaries.
  file:
    path: "{{ optDirectory }}"
    state: directory
    owner: pi
    group: pi

- name: Download the application WAR file.
  get_url:
    url: https://gitlab.com/onebeartoe/electronics/-/jobs/905577676/artifacts/raw/neje-engrave/target/neje-engrave-0.0.1-SNAPSHOT.war
    dest: "{{ optDirectory }}"
