
- name: ansible is present
  apt:
    name: ansible
    force: yes
  tags: [apt-prerequisites]

- name: build-essential is installed
  apt:
      name: build-essential
  tags: [apt-prerequisites]

- name: qt5-qmake is installed
  apt:
      name: qt5-qmake
  tags: [apt-prerequisites]

- name: qtbase5-dev is installed
  apt:
      name: qtbase5-dev
  tags: [apt-prerequisites]

- name: libqt5serialport5-dev is installed
  apt:
      name: libqt5serialport5-dev
  tags: [apt-prerequisites]

- name: openjdk-8-jdk is installed
  apt:
      name: openjdk-8-jdk
  tags: [apt-prerequisites]

- name: git is installed
  apt:
      name: git
  tags: [apt-prerequisites]
